[MeterBand1]
Meter = BitMap
MeasureName = MeasureBand19
MeterStyle = BandStyle
TransformationMatrix = (0.4725*#Scale#);(0*#Scale#);(0*#Scale#);(0.175*#Scale#);(94.8025*#Scale#);(7.5*#Scale#)
X = 0
Y = 0

[MeterBand2]
Meter = BitMap
MeasureName = MeasureBand17
MeterStyle = BandStyle
TransformationMatrix = (0.47036*#Scale#);(-0.044915*#Scale#);(0.016635*#Scale#);(0.174208*#Scale#);(86.033318*#Scale#);(8.412871*#Scale#)
X = 0
Y = 0

[MeterBand3]
Meter = BitMap
MeasureName = MeasureBand18
MeterStyle = BandStyle
TransformationMatrix = (0.463963*#Scale#);(-0.08942*#Scale#);(0.033119*#Scale#);(0.171838*#Scale#);(77.390682*#Scale#);(10.155168*#Scale#)
X = 0
Y = 0

[MeterBand4]
Meter = BitMap
MeasureName = MeasureBand15
MeterStyle = BandStyle
TransformationMatrix = (0.45336*#Scale#);(-0.13312*#Scale#);(0.049303*#Scale#);(0.167911*#Scale#);(68.952811*#Scale#);(12.711243*#Scale#)
X = 0
Y = 0

[MeterBand5]
Meter = BitMap
MeasureName = MeasureBand13
MeterStyle = BandStyle
TransformationMatrix = (0.438655*#Scale#);(-0.175613*#Scale#);(0.065041*#Scale#);(0.162464*#Scale#);(60.795992*#Scale#);(16.057744*#Scale#)
X = 0
Y = 0

[MeterBand6]
Meter = BitMap
MeasureName = MeasureBand12
MeterStyle = BandStyle
TransformationMatrix = (0.419975*#Scale#);(-0.216513*#Scale#);(0.08019*#Scale#);(0.155546*#Scale#);(52.994245*#Scale#);(20.164403*#Scale#)
X = 0
Y = 0

[MeterBand7]
Meter = BitMap
MeasureName = MeasureBand10
MeterStyle = BandStyle
TransformationMatrix = (0.39749*#Scale#);(-0.255455*#Scale#);(0.094612*#Scale#);(0.147219*#Scale#);(45.618335*#Scale#);(24.994093*#Scale#)
X = 0
Y = 0

[MeterBand8]
Meter = BitMap
MeasureName = MeasureBand8
MeterStyle = BandStyle
TransformationMatrix = (0.371408*#Scale#);(-0.29208*#Scale#);(0.108178*#Scale#);(0.137559*#Scale#);(38.734755*#Scale#);(30.503023*#Scale#)
X = 0
Y = 0

[MeterBand9]
Meter = BitMap
MeasureName = MeasureBand6
MeterStyle = BandStyle
TransformationMatrix = (0.341965*#Scale#);(-0.326063*#Scale#);(0.120764*#Scale#);(0.126653*#Scale#);(32.406022*#Scale#);(36.641368*#Scale#)
X = 0
Y = 0

[MeterBand10]
Meter = BitMap
MeasureName = MeasureBand4
MeterStyle = BandStyle
TransformationMatrix = (0.309423*#Scale#);(-0.357093*#Scale#);(0.132256*#Scale#);(0.114601*#Scale#);(26.689565*#Scale#);(43.353322*#Scale#)
X = 0
Y = 0

[MeterBand11]
Meter = BitMap
MeasureName = MeasureBand4
MeterStyle = BandStyle
TransformationMatrix = (0.274078*#Scale#);(-0.384888*#Scale#);(0.142551*#Scale#);(0.10151*#Scale#);(21.63685*#Scale#);(50.578504*#Scale#)
X = 0
Y = 0

[MeterBand12]
Meter = BitMap
MeasureName = MeasureBand6
MeterStyle = BandStyle
TransformationMatrix = (0.23625*#Scale#);(-0.409198*#Scale#);(0.151554*#Scale#);(0.0875*#Scale#);(17.29396*#Scale#);(58.25115*#Scale#)
X = 0
Y = 0

[MeterBand13]
Meter = BitMap
MeasureName = MeasureBand8
MeterStyle = BandStyle
TransformationMatrix = (0.196283*#Scale#);(-0.4298*#Scale#);(0.159186*#Scale#);(0.072698*#Scale#);(13.699897*#Scale#);(66.301859*#Scale#)
X = 0
Y = 0

[MeterBand14]
Meter = BitMap
MeasureName = MeasureBand10
MeterStyle = BandStyle
TransformationMatrix = (0.154543*#Scale#);(-0.446513*#Scale#);(0.165375*#Scale#);(0.057237*#Scale#);(10.887482*#Scale#);(74.657824*#Scale#)
X = 0
Y = 0

[MeterBand15]
Meter = BitMap
MeasureName = MeasureBand12
MeterStyle = BandStyle
TransformationMatrix = (0.111395*#Scale#);(-0.459183*#Scale#);(0.170067*#Scale#);(0.041258*#Scale#);(8.882093*#Scale#);(83.243261*#Scale#)
X = 0
Y = 0

[MeterBand16]
Meter = BitMap
MeasureName = MeasureBand13
MeterStyle = BandStyle
TransformationMatrix = (0.067243*#Scale#);(-0.46769*#Scale#);(0.173219*#Scale#);(0.024905*#Scale#);(7.701818*#Scale#);(91.980495*#Scale#)
X = 0
Y = 0

[MeterBand17]
Meter = BitMap
MeasureName = MeasureBand15
MeterStyle = BandStyle
TransformationMatrix = (0.02248*#Scale#);(-0.471963*#Scale#);(0.174802*#Scale#);(0.008327*#Scale#);(7.357465*#Scale#);(100.790236*#Scale#)
X = 0
Y = 0

[MeterBand18]
Meter = BitMap
MeasureName = MeasureBand17
MeterStyle = BandStyle
TransformationMatrix = (-0.02248*#Scale#);(-0.471963*#Scale#);(0.174802*#Scale#);(-0.008327*#Scale#);(7.852036*#Scale#);(109.592959*#Scale#)
X = 0
Y = 0

[MeterBand19]
Meter = BitMap
MeasureName = MeasureBand19
MeterStyle = BandStyle
TransformationMatrix = (-0.067243*#Scale#);(-0.46769*#Scale#);(0.173219*#Scale#);(-0.024905*#Scale#);(9.181163*#Scale#);(118.308691*#Scale#)
X = 0
Y = 0

[MeterBand20]
Meter = BitMap
MeasureName = MeasureBand31
MeterStyle = BandStyle
TransformationMatrix = (-0.111395*#Scale#);(-0.459183*#Scale#);(0.170067*#Scale#);(-0.041258*#Scale#);(11.332782*#Scale#);(126.858744*#Scale#)
X = 0
Y = 0

[MeterBand21]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = BandStyle
TransformationMatrix = (-0.154543*#Scale#);(-0.446513*#Scale#);(0.165375*#Scale#);(-0.057237*#Scale#);(14.287408*#Scale#);(135.165451*#Scale#)
X = 0
Y = 0

[MeterBand22]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = BandStyle
TransformationMatrix = (-0.196283*#Scale#);(-0.4298*#Scale#);(0.159186*#Scale#);(-0.072698*#Scale#);(18.018121*#Scale#);(143.153748*#Scale#)
X = 0
Y = 0

[MeterBand23]
Meter = BitMap
MeasureName = MeasureBand27
MeterStyle = BandStyle
TransformationMatrix = (-0.23625*#Scale#);(-0.409198*#Scale#);(0.151554*#Scale#);(-0.0875*#Scale#);(22.491455*#Scale#);(150.751195*#Scale#)
X = 0
Y = 0

[MeterBand24]
Meter = BitMap
MeasureName = MeasureBand26
MeterStyle = BandStyle
TransformationMatrix = (-0.274078*#Scale#);(-0.384888*#Scale#);(0.142551*#Scale#);(-0.10151*#Scale#);(27.666546*#Scale#);(157.889023*#Scale#)
X = 0
Y = 0

[MeterBand25]
Meter = BitMap
MeasureName = MeasureBand25
MeterStyle = BandStyle
TransformationMatrix = (-0.309423*#Scale#);(-0.357093*#Scale#);(0.132256*#Scale#);(-0.114601*#Scale#);(33.496862*#Scale#);(164.502703*#Scale#)
X = 0
Y = 0

[MeterBand26]
Meter = BitMap
MeasureName = MeasureBand24
MeterStyle = BandStyle
TransformationMatrix = (-0.341965*#Scale#);(-0.326063*#Scale#);(0.120764*#Scale#);(-0.126653*#Scale#);(39.929251*#Scale#);(170.532002*#Scale#)
X = 0
Y = 0

[MeterBand27]
Meter = BitMap
MeasureName = MeasureBand23
MeterStyle = BandStyle
TransformationMatrix = (-0.371408*#Scale#);(-0.29208*#Scale#);(0.108178*#Scale#);(-0.137559*#Scale#);(46.905738*#Scale#);(175.922741*#Scale#)
X = 0
Y = 0

[MeterBand28]
Meter = BitMap
MeasureName = MeasureBand22
MeterStyle = BandStyle
TransformationMatrix = (-0.39749*#Scale#);(-0.255455*#Scale#);(0.094612*#Scale#);(-0.147219*#Scale#);(54.363127*#Scale#);(180.625913*#Scale#)
X = 0
Y = 0

[MeterBand29]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = BandStyle
TransformationMatrix = (-0.419975*#Scale#);(-0.216513*#Scale#);(0.08019*#Scale#);(-0.155546*#Scale#);(62.23369*#Scale#);(184.598875*#Scale#)
X = 0
Y = 0

[MeterBand30]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = BandStyle
TransformationMatrix = (-0.438655*#Scale#);(-0.175613*#Scale#);(0.065041*#Scale#);(-0.162464*#Scale#);(70.446394*#Scale#);(187.805716*#Scale#)
X = 0
Y = 0

[MeterBand31]
Meter = BitMap
MeasureName = MeasureBand21
MeterStyle = BandStyle
TransformationMatrix = (-0.45336*#Scale#);(-0.13312*#Scale#);(0.049303*#Scale#);(-0.167911*#Scale#);(78.926732*#Scale#);(190.217396*#Scale#)
X = 0
Y = 0

[MeterBand32]
Meter = BitMap
MeasureName = MeasureBand22
MeterStyle = BandStyle
TransformationMatrix = (-0.463963*#Scale#);(-0.08942*#Scale#);(0.033119*#Scale#);(-0.171838*#Scale#);(87.597847*#Scale#);(191.812076*#Scale#)
X = 0
Y = 0

[MeterBand33]
Meter = BitMap
MeasureName = MeasureBand23
MeterStyle = BandStyle
TransformationMatrix = (-0.47036*#Scale#);(-0.044915*#Scale#);(0.016635*#Scale#);(-0.174208*#Scale#);(96.38124*#Scale#);(192.575256*#Scale#)
X = 0
Y = 0

[MeterBand34]
Meter = BitMap
MeasureName = MeasureBand24
MeterStyle = BandStyle
TransformationMatrix = (-0.4725*#Scale#);(-0*#Scale#);(0*#Scale#);(-0.175*#Scale#);(105.1975*#Scale#);(192.5*#Scale#)
X = 0
Y = 0

[MeterBand35]
Meter = BitMap
MeasureName = MeasureBand25
MeterStyle = BandStyle
TransformationMatrix = (-0.47036*#Scale#);(0.044915*#Scale#);(-0.016635*#Scale#);(-0.174208*#Scale#);(113.966682*#Scale#);(191.587129*#Scale#)
X = 0
Y = 0

[MeterBand36]
Meter = BitMap
MeasureName = MeasureBand26
MeterStyle = BandStyle
TransformationMatrix = (-0.463963*#Scale#);(0.08942*#Scale#);(-0.033119*#Scale#);(-0.171838*#Scale#);(122.60932*#Scale#);(189.844832*#Scale#)
X = 0
Y = 0

[MeterBand37]
Meter = BitMap
MeasureName = MeasureBand27
MeterStyle = BandStyle
TransformationMatrix = (-0.45336*#Scale#);(0.13312*#Scale#);(-0.049303*#Scale#);(-0.167911*#Scale#);(131.047189*#Scale#);(187.288757*#Scale#)
X = 0
Y = 0

[MeterBand38]
Meter = BitMap
MeasureName = MeasureBand28
MeterStyle = BandStyle
TransformationMatrix = (-0.438655*#Scale#);(0.175613*#Scale#);(-0.065041*#Scale#);(-0.162464*#Scale#);(139.204008*#Scale#);(183.942257*#Scale#)
X = 0
Y = 0

[MeterBand39]
Meter = BitMap
MeasureName = MeasureBand29
MeterStyle = BandStyle
TransformationMatrix = (-0.419975*#Scale#);(0.216513*#Scale#);(-0.08019*#Scale#);(-0.155546*#Scale#);(147.005755*#Scale#);(179.835598*#Scale#)
X = 0
Y = 0

[MeterBand40]
Meter = BitMap
MeasureName = MeasureBand30
MeterStyle = BandStyle
TransformationMatrix = (-0.39749*#Scale#);(0.255455*#Scale#);(-0.094612*#Scale#);(-0.147219*#Scale#);(154.381665*#Scale#);(175.005908*#Scale#)
X = 0
Y = 0

[MeterBand41]
Meter = BitMap
MeasureName = MeasureBand31
MeterStyle = BandStyle
TransformationMatrix = (-0.371408*#Scale#);(0.29208*#Scale#);(-0.108178*#Scale#);(-0.137559*#Scale#);(161.265246*#Scale#);(169.496977*#Scale#)
X = 0
Y = 0

[MeterBand42]
Meter = BitMap
MeasureName = MeasureBand32
MeterStyle = BandStyle
TransformationMatrix = (-0.341965*#Scale#);(0.326063*#Scale#);(-0.120764*#Scale#);(-0.126653*#Scale#);(167.593978*#Scale#);(163.358633*#Scale#)
X = 0
Y = 0

[MeterBand43]
Meter = BitMap
MeasureName = MeasureBand33
MeterStyle = BandStyle
TransformationMatrix = (-0.309423*#Scale#);(0.357093*#Scale#);(-0.132256*#Scale#);(-0.114601*#Scale#);(173.310436*#Scale#);(156.646679*#Scale#)
X = 0
Y = 0

[MeterBand44]
Meter = BitMap
MeasureName = MeasureBand34
MeterStyle = BandStyle
TransformationMatrix = (-0.274078*#Scale#);(0.384888*#Scale#);(-0.142551*#Scale#);(-0.10151*#Scale#);(178.363151*#Scale#);(149.421497*#Scale#)
X = 0
Y = 0

[MeterBand45]
Meter = BitMap
MeasureName = MeasureBand35
MeterStyle = BandStyle
TransformationMatrix = (-0.23625*#Scale#);(0.409198*#Scale#);(-0.151554*#Scale#);(-0.0875*#Scale#);(182.70604*#Scale#);(141.748851*#Scale#)
X = 0
Y = 0

[MeterBand46]
Meter = BitMap
MeasureName = MeasureBand36
MeterStyle = BandStyle
TransformationMatrix = (-0.196283*#Scale#);(0.4298*#Scale#);(-0.159186*#Scale#);(-0.072698*#Scale#);(186.300104*#Scale#);(133.698141*#Scale#)
X = 0
Y = 0

[MeterBand47]
Meter = BitMap
MeasureName = MeasureBand37
MeterStyle = BandStyle
TransformationMatrix = (-0.154543*#Scale#);(0.446513*#Scale#);(-0.165375*#Scale#);(-0.057237*#Scale#);(189.11252*#Scale#);(125.342177*#Scale#)
X = 0
Y = 0

[MeterBand48]
Meter = BitMap
MeasureName = MeasureBand38
MeterStyle = BandStyle
TransformationMatrix = (-0.111395*#Scale#);(0.459183*#Scale#);(-0.170067*#Scale#);(-0.041258*#Scale#);(191.117907*#Scale#);(116.75674*#Scale#)
X = 0
Y = 0

[MeterBand49]
Meter = BitMap
MeasureName = MeasureBand39
MeterStyle = BandStyle
TransformationMatrix = (-0.067243*#Scale#);(0.46769*#Scale#);(-0.173219*#Scale#);(-0.024905*#Scale#);(192.298183*#Scale#);(108.019505*#Scale#)
X = 0
Y = 0

[MeterBand50]
Meter = BitMap
MeasureName = MeasureBand40
MeterStyle = BandStyle
TransformationMatrix = (-0.02248*#Scale#);(0.471963*#Scale#);(-0.174802*#Scale#);(-0.008327*#Scale#);(192.642535*#Scale#);(99.209765*#Scale#)
X = 0
Y = 0

[MeterBand51]
Meter = BitMap
MeasureName = MeasureBand41
MeterStyle = BandStyle
TransformationMatrix = (0.02248*#Scale#);(0.471963*#Scale#);(-0.174802*#Scale#);(0.008327*#Scale#);(192.147964*#Scale#);(90.407042*#Scale#)
X = 0
Y = 0

[MeterBand52]
Meter = BitMap
MeasureName = MeasureBand42
MeterStyle = BandStyle
TransformationMatrix = (0.067243*#Scale#);(0.46769*#Scale#);(-0.173219*#Scale#);(0.024905*#Scale#);(190.818838*#Scale#);(81.691309*#Scale#)
X = 0
Y = 0

[MeterBand53]
Meter = BitMap
MeasureName = MeasureBand43
MeterStyle = BandStyle
TransformationMatrix = (0.111395*#Scale#);(0.459183*#Scale#);(-0.170067*#Scale#);(0.041258*#Scale#);(188.667218*#Scale#);(73.141257*#Scale#)
X = 0
Y = 0

[MeterBand54]
Meter = BitMap
MeasureName = MeasureBand44
MeterStyle = BandStyle
TransformationMatrix = (0.154543*#Scale#);(0.446513*#Scale#);(-0.165375*#Scale#);(0.057237*#Scale#);(185.712594*#Scale#);(64.83455*#Scale#)
X = 0
Y = 0

[MeterBand55]
Meter = BitMap
MeasureName = MeasureBand45
MeterStyle = BandStyle
TransformationMatrix = (0.196283*#Scale#);(0.4298*#Scale#);(-0.159186*#Scale#);(0.072698*#Scale#);(181.98188*#Scale#);(56.846252*#Scale#)
X = 0
Y = 0

[MeterBand56]
Meter = BitMap
MeasureName = MeasureBand46
MeterStyle = BandStyle
TransformationMatrix = (0.23625*#Scale#);(0.409198*#Scale#);(-0.151554*#Scale#);(0.0875*#Scale#);(177.508545*#Scale#);(49.248806*#Scale#)
X = 0
Y = 0

[MeterBand57]
Meter = BitMap
MeasureName = MeasureBand47
MeterStyle = BandStyle
TransformationMatrix = (0.274078*#Scale#);(0.384888*#Scale#);(-0.142551*#Scale#);(0.10151*#Scale#);(172.333455*#Scale#);(42.110978*#Scale#)
X = 0
Y = 0

[MeterBand58]
Meter = BitMap
MeasureName = MeasureBand48
MeterStyle = BandStyle
TransformationMatrix = (0.309423*#Scale#);(0.357093*#Scale#);(-0.132256*#Scale#);(0.114601*#Scale#);(166.503139*#Scale#);(35.497298*#Scale#)
X = 0
Y = 0

[MeterBand59]
Meter = BitMap
MeasureName = MeasureBand49
MeterStyle = BandStyle
TransformationMatrix = (0.341965*#Scale#);(0.326063*#Scale#);(-0.120764*#Scale#);(0.126653*#Scale#);(160.070749*#Scale#);(29.467999*#Scale#)
X = 0
Y = 0

[MeterBand60]
Meter = BitMap
MeasureName = MeasureBand50
MeterStyle = BandStyle
TransformationMatrix = (0.371408*#Scale#);(0.29208*#Scale#);(-0.108178*#Scale#);(0.137559*#Scale#);(153.094263*#Scale#);(24.077259*#Scale#)
X = 0
Y = 0

[MeterBand61]
Meter = BitMap
MeasureName = MeasureBand44
MeterStyle = BandStyle
TransformationMatrix = (0.39749*#Scale#);(0.255455*#Scale#);(-0.094612*#Scale#);(0.147219*#Scale#);(145.636873*#Scale#);(19.374088*#Scale#)
X = 0
Y = 0

[MeterBand62]
Meter = BitMap
MeasureName = MeasureBand42
MeterStyle = BandStyle
TransformationMatrix = (0.419975*#Scale#);(0.216513*#Scale#);(-0.08019*#Scale#);(0.155546*#Scale#);(137.76631*#Scale#);(15.401126*#Scale#)
X = 0
Y = 0

[MeterBand63]
Meter = BitMap
MeasureName = MeasureBand40
MeterStyle = BandStyle
TransformationMatrix = (0.438655*#Scale#);(0.175613*#Scale#);(-0.065041*#Scale#);(0.162464*#Scale#);(129.553606*#Scale#);(12.194285*#Scale#)
X = 0
Y = 0

[MeterBand64]
Meter = BitMap
MeasureName = MeasureBand38
MeterStyle = BandStyle
TransformationMatrix = (0.45336*#Scale#);(0.13312*#Scale#);(-0.049303*#Scale#);(0.167911*#Scale#);(121.073268*#Scale#);(9.782604*#Scale#)
X = 0
Y = 0

[MeterBand65]
Meter = BitMap
MeasureName = MeasureBand36
MeterStyle = BandStyle
TransformationMatrix = (0.463963*#Scale#);(0.08942*#Scale#);(-0.033119*#Scale#);(0.171838*#Scale#);(112.402155*#Scale#);(8.187924*#Scale#)
X = 0
Y = 0

[MeterBand66]
Meter = BitMap
MeasureName = MeasureBand34
MeterStyle = BandStyle
TransformationMatrix = (0.47036*#Scale#);(0.044915*#Scale#);(-0.016635*#Scale#);(0.174208*#Scale#);(103.61876*#Scale#);(7.424744*#Scale#)
X = 0
Y = 0
